services:
  prometheus:
    image: prom/prometheus
    container_name: deploy-io_prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    
    ports:
      - 9090:9090
    
    restart: unless-stopped
    
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: deploy-io_grafana
    
    ports:
      - 3030:3000
    
    restart: unless-stopped
    
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana

    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - graf-data:/var/lib/grafana

volumes:
  prom-data:
    driver: local
  graf-data:
    driver: local